metadataName: "ballast-deployment"

appLabel: "ballast-pod"

replicaCount: 1

resources:
  requests:
    cpu: 500m
    memory: 20Mi

imagestore:
  busybox:
    registry: ""
    repository: library/busybox
    tag: latest

priorityClassName: "ballast"