{{- if .Values.secrets }}
{{- if .Values.secrets.containerregistry }}
apiVersion: v1
kind: Secret
metadata:
  name: adaptation-registry-credential
  namespace: {{.Values.adaptationservice.namespace}}
data:
  .dockerconfigjson: {{ .Values.secrets.containerregistry.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson
{{- end }}
{{- end }}    