apiVersion: v1
kind: Service
metadata:
  name: icap-service
  labels:
    app: {{ .Values.icapservice.applabel }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.icapservice.applabel }}
  ports:
  - port: 1344
    protocol: TCP
    name: openport
    targetPort: 1344
  - port: 1345
    protocol: TCP
    nodePort: 32323
    name: tlsport
    targetPort: 1345
