apiVersion: v1
kind: Service
metadata:
  name: icap-service
  labels:
    app: {{ .Values.icapservice.applabel }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.icapservice.applabel }}
    ports:
  - name: openport
    port: 1344
    protocol: TCP
    targetPort: 1344
  - name: tlsport
    nodePort: 32323
    port: 1345
    protocol: TCP
    targetPort: 1345