apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: mvp-icap-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mvp-icap-service
  minReplicas: {{ .Values.icapservice.replicas.min }}
  maxReplicas: {{ .Values.icapservice.replicas.max }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75