{{- if .Values.secrets }}
{{- if .Values.secrets.mvpicapservice }}
apiVersion: v1
kind: Secret
metadata:
  name: icap-service-tls-config
  namespace: {{.Values.adaptationservice.namespace}}
type: kubernetes.io/tls
data:
  tls.crt: |
    {{ .Values.secrets.mvpicapservice.tlsCert }}
  tls.key: |
    {{ .Values.secrets.mvpicapservice.tlsKey }}
{{- end }}
{{- end }}    