apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  labels:
    app: {{ .Values.rabbitmqService.app }}
    component: {{ .Values.rabbitmqService.component }}
  name: {{ .Values.rabbitmqService.name }}
spec:
 replicas: 3
 image: {{ .Values.imagestore.rabbitmq.registry }}{{ .Values.imagestore.rabbitmq.repository }}:{{ .Values.imagestore.rabbitmq.tag }}
 imagePullSecrets:
  - name: adaptation-registry-credential
 tolerations:
   - key: dedicated
     value: stateful
     operator: Equal
     effect: NoSchedule
 affinity:
   podAntiAffinity:
     preferredDuringSchedulingIgnoredDuringExecution:
     - weight: 100
       podAffinityTerm:
         labelSelector:
          matchExpressions:
          - key: {{ .Values.rabbitmqService.key }}
            operator: In
            values:
            - store
         topologyKey: kubernetes.io/hostname
 persistence:
   storageClassName: azuredisk
   storage: 10Gi



