apiVersion: v1
kind: Secret
metadata:
  name: transactionstoresecret
type: Opaque
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  accountName: {{ .Values.secrets.transactionstore.accountName }}
  accountKey: {{ .Values.secrets.transactionstore.accountKey }}