---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-transactionstore
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.transactionstore.storage }}
  selector:
    matchLabels:
      usage: pv-transactionstore