apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  labels: 
    app: {{ .Values.rabbitmqService.app }}
    component: {{ .Values.rabbitmqService.component }}
  name: {{ .Values.rabbitmqService.name }}
spec:
 replicas: 3
 affinity:
   podAntiAffinity:
     preferredDuringSchedulingIgnoredDuringExecution: 
     - weight: 100  
       podAffinityTerm:
         labelSelector:
          matchExpressions:
          - key: {{ .Values.rabbitmqService.key }}
            operator: In
            values:
            - store
         topologyKey: kubernetes.io/hostname
