apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: management-ui
  name: {{ .Values.managementui.service.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.managementui.deployment.name }}
  ports:
    - port: 443
      nodePort: 32323
      targetPort: 443