apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{.Values.metadataName}}
  labels:
    app: {{.Values.appLabel}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{.Values.metadataName}}-clusterrole
subjects:
  - kind: ServiceAccount
    name: {{.Values.serviceAccountName}}
    namespace: kube-system