apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Values.metadataName}}-configmaker
  namespace: kube-system
spec:
  template:
    spec:
      serviceAccountName: {{.Values.serviceAccountName}}
      containers:
      - image: bskim45/helm-kubectl-jq:3.3.4
        name: {{.Values.metadataName}}-configmaker
        command: [ "/bin/bash"  ]
        args: 
        - "-c"
        - |
          apk add curl;
          kubectl create configmap -n kube-system clusternamemap --from-literal=resourcegroup=$(curl -H Metadata:true http://169.254.169.254/metadata/instance/compute?api-version=2020-09-01 | jq -r '.resourceGroupName') --from-literal=clustername=$(kubectl get nodes -o json | jq -r '.items[0].metadata.labels["k8s.io/cluster"]');
      restartPolicy: OnFailure
