apiVersion: v1
kind: Secret
metadata:
  name: autoscaler-registry-credential
  namespace: kube-system
data:
  .dockerconfigjson: {{ .Values.secrets.containerregistry.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson