apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{.Values.metadataName}}
  namespace: kube-system
  labels:
    app: {{.Values.appLabel}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{.Values.metadataName}}-role
subjects:
  - kind: ServiceAccount
    name: {{.Values.serviceAccountName}}
    namespace: kube-system