apiVersion: v1
data:
  ClientID: {{.Values.secrets.azureSecrets.clientId | b64enc}}
  ClientSecret: {{.Values.secrets.azureSecrets.clientSecret | b64enc}}
  SubscriptionID: {{.Values.secrets.azureSecrets.subscriptionId | b64enc}}
  TenantID: {{.Values.secrets.azureSecrets.tenantId  | b64enc}}
kind: Secret
metadata:
  name: {{.Values.metadataName}}
  namespace: kube-system