apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.transactioneventapi.fullnameOverride }}
  labels:
    app: {{ template "transactioneventapi.name" . }}
    chart: {{ template "transactioneventapi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.transactioneventapi.service.type }}
  ports:
    - port: {{ .Values.transactioneventapi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "transactioneventapi.name" . }}
    release: {{ .Release.Name }}
