apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.identitymanagementservice.name }}
  labels:
    {{- include "identitymanagementservice.labels" . | nindent 4 }}
{{- if .Values.identitymanagementservice.service.labels }}
{{ toYaml .Values.identitymanagementservice.service.labels | indent 4}}
{{- end }}    
spec:
  type: NodePort
  ports:
    - port: 443
      protocol: TCP
      nodePort: 32323
      targetPort: 443
  selector:
    {{- include "identitymanagementservice.matchLabels" . | nindent 4 }}
