apiVersion: v1
kind: Secret
metadata:
  name: overprovisioning-registry-credential
data:
  .dockerconfigjson: {{ .Values.secrets.containerregistry.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson