apiVersion: v1
kind: ConfigMap
metadata:
  name: icap-tcp-traffic
data:
  {{ .Values.service.icapPort }}: "{{ .Values.icapBackend.serviceNamespace }}/{{ .Values.icapBackend.serviceName }}:{{ .Values.service.icapPort }}"