apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-default-backend
  labels:
    app: {{.Values.appLabel}}
    {{- toYaml .Values.addLabels.controller | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: {{.Values.appLabel}}
    {{- toYaml .Values.addLabels.controller | nindent 4 }}
