apiVersion: v1
kind: Service
metadata:
  name: {{.Values.appLabel}}
  labels:
    app: {{.Values.appLabel}}
spec:
  selector:
    app: {{.Values.appLabel}}
    {{- toYaml .Values.addLabels.controller | nindent 4 }}
  ports:
  - port: {{.Values.service.httpPort}}
    targetPort: {{.Values.container.httpPort}}
    nodePort: {{.Values.service.httpNodePort}}
    name: http
  - port: {{.Values.service.httpsPort}}
    targetPort: {{.Values.container.httpsPort}}
    nodePort: {{.Values.service.httpsNodePort}}
    name: https
  - port: {{ .Values.service.icapPort }}
    name: icap-tcp
    targetPort: {{ .Values.service.icapPort }}
    protocol: TCP
  type: {{.Values.service.type}}

