apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  name: {{ .Values.filedropapi.name }}
spec:
  rules:
    - http:
        paths:
          - path: /api
            backend:
              serviceName: {{ .Values.filedropapi.name }}
              servicePort: http
