{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Values.filedropui.name }}
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.filedropui.name }}
              servicePort: http