apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.filedropui.name }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: {{ .Values.filedropui.name  }}