apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.filedropui.name }}
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: {{ .Values.filedropui.name  }}