apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "transaction-event-api.fullname" . }}
  labels:
    {{- include "transaction-event-api.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.transactioneventapi.replicaCount }}
  selector:
    matchLabels:
      {{- include "transaction-event-api.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "transaction-event-api.labels" . | nindent 8 }}
      annotations:
        buildID: {{ .Values.buildID | default "" | quote }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.imagestore.transactioneventapi.registry }}{{ .Values.imagestore.transactioneventapi.repository }}:{{ .Values.imagestore.transactioneventapi.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.transactioneventapi.deployment.containerPort }}
              protocol: TCP
          {{- if .Values.transactioneventapi.probes.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- end }}
          envFrom:
          - configMapRef:
              name: {{ template "transaction-event-api.fullname" . }}         
          env:
            - name: TransactionStoreConnectionStringCsv
              valueFrom:
                secretKeyRef:
                  name: transactionstoresecret
                  key: TransactionStoreConnectionStringCsv
            {{- $root := . }}
            {{- range $ref, $values := .Values.transactioneventapi.secrets }}
            {{- range $key, $value := $values }}
            - name: {{ $ref }}_{{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "transactioneventapi.fullname" $root }}-{{ $ref | lower }}
                  key: {{ $key }}
            {{- end }}
            {{- end }}
          resources:
{{ toYaml .Values.transactioneventapi.resources | indent 12 }}
    {{- with .Values.transactioneventapi.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.transactioneventapi.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.transactioneventapi.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      imagePullSecrets:
        - name: transactioneventapi-registry-credential