apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-registry-credential
  namespace: {{.Values.namespace}}
data:
  .dockerconfigjson: {{ .Values.secrets.containerregistry.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson