apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adaptation-service
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/filetrust/icap-infrastructure
    targetRevision: HEAD
    path: adaptation
    directory:
      recurse: true
  destination:
    server: https://gw-icap-k8s-f17703a9.hcp.uksouth.azmk8s.io:443
    namespace: icap-adaptation
  syncPolicy:
    automated:
      prune: false
      selfHeal: false