apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adaptation-service
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/filetrust/icap-infrastructure/tree/main
    targetRevision: MAIN
    path: adaptation
    directory:
      recurse: true
  destination:
    server: {{ .values.spec.destination.server }}
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: false