imagestore:
  cainjector:
    registry: quay.io/
    repository: jetstack/cert-manager-cainjector
    tag: v1.1.0
  cacontroller:
    registry: quay.io/
    repository: jetstack/cert-manager-controller
    tag: v1.1.0
  cawebhook:
    registry: quay.io/
    repository: jetstack/cert-manager-webhook
    tag: v1.1.0

secrets:
  containerregistry:
    dockerconfigjson: "<<https://gw-icap-keyvault.vault.azure.net/secrets/az-registry-dockerconfig>>"