{{- if .Values.elasticsearch.enabled }}
{{- if .Values.elasticsearch.maxUnavailable }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "{{ template "elasticsearch.uname" . }}-pdb"
spec:
  maxUnavailable: {{ .Values.elasticsearch.maxUnavailable }}
  selector:
    matchLabels:
      app: "{{ template "elasticsearch.uname" . }}"
{{- end }}
{{- end }}
