---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-policystore
spec:
  storageClassName: azurefile
  accessModes: [ "ReadWriteMany" ]
  resources:
    requests:
      storage: {{ .Values.policymanagementapi.storage }}
#  selector:
#    matchLabels:
#      usage: pv-policystore