environment:
deployment:
  name: icap-management-ui
  port: 8080
service:
  name: icap-management-ui-service
  port: 80
imagestore:
  icapmanagementui:
    registry: ""
    repository: glasswallsolutions/icap-management-ui
    tag: main-latest
secrets:
  containerregistry:
    dockerconfigjson: "$$REPLACE WITH BASE64 .DOCKERCONFIGJSON$$"

