{{- $root := . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nginx.fullname" . }}
data:
  nginx.conf: |-
    events {}
    http {
        client_max_body_size 0;
        server {
            location / {
                proxy_pass http://file-drop-ui-service/;
            }
            location /api {
                proxy_pass http://file-drop-api-service/;
            }
        }
    }